name: triggered workflow

on:
   workflow_dispatch:
    inputs:
        run-tests:
            description: "run test"
            type: boolean
            default: true
        test-type:
            description: "test"
            type: choice
            options:
                - t1
                - t2
                - t3
            required: true    

jobs:
    debug_job:
        runs-on: ubuntu-latest
        steps:
        - name: checkout repo
          run: echo "testing"
